### PR TITLE
Add specimen image source file

### PR DESCRIPTION
**Pull request by eliheuer**
The current specimen image doesn't have a source file. This PR adds a Python([DrawBot](https://www.drawbot.com/)) source file for the specimen image. I'm not sure if DrawBot is the right choice for this, I would be interested in seeing any alternative PRs for this using other systems.

Some reasons I think including source files in open-source font repositories is worth encouraging:

- Building new specimens can be integrated into the [GF-UFR](https://github.com/googlefonts/Unified-Font-Repository) build system or automated with shell scripts by designers
- People who fork the project have image and document sources to work with
- Helps introduce new users to DrawBot and other similar text-based typesetting systems like LaTeX, SILE, etc
- DrawBot has good support for variable fonts and animated specimens
- Many designers know DrawBot already from various educational environments
- DrawBot has a free GUI editor for macOS
- [DrawBot Skia](https://github.com/justvanrossum/drawbot-skia) is making progress(for building on Linux)

image1

### CODE REVIEW

**Comment by simoncozens** [comment]
I like this for generating *sample images* (publicity etc.), and I think it looks really great. I love the idea of exposing users to the possibilities of Drawbot and scriptable image generation.

 I think we need something more for *specimens*, though. Possibly SILE, possibly pagebot, or possibly wktopdf or similar on top of the existing HTML proof generator. Can we talk more about that on Thursday?

**Comment by RosaWagner** [comment]
Yes to all.

**Comment by eliheuer** [comment]
Sounds good. Having a standard GF PDF specimen in this repo with spacing strings, sample text, etc would be nice. If it is automatically generated as part of the build process things like Git commit and version number could be included on the cover page. SILE might be a good way to go for that.

**Comment by simoncozens** [comment]
It’s what I do for my own repos. :-)

**Comment by eliheuer** [comment]
For variable font animations, [Coldtype](https://github.com/goodhertz/coldtype) might be worth looking at for this as a cross-platform DrawBot alternative. I will try to make another PR adding an animated specimen example using DrawBot or Coldtype at a later date.

The DrawBot source in this PR has a function that makes it easier to create looping animations by remapping the VF axis range to a sine wave's range.

``` Python
# REMAP INPUT RANGE TO VF AXIS RANGE
# (E.G. SINE WAVE(-1,1) to WGHT(100,900))
def remap(value, inputMin, inputMax, outputMin, outputMax):
    inputSpan = inputMax - inputMin  # FIND INPUT RANGE SPAN
    outputSpan = outputMax - outputMin  # FIND OUTPUT RANGE SPAN
    valueScaled = float(value - inputMin) / float(inputSpan)
    return outputMin + (valueScaled * outputSpan)
```

**Review by RosaWagner — APPROVED** [review]

**Comment by simoncozens** [comment]
I also want these automatically generated as part of the build, or at least build targets to recreate them, with drawbot-skia or a macOS runner or whatever.

**Comment by simoncozens** [comment]
@googlebot I consent.

**Comment by simoncozens** [comment]
@googlebot I consent.

**Pull request merged**
